# Ler um modelo registado

Neste notebook iremos utilizar o modelo que registámos no notebook anterior para fazer previsões.

In [1]:
import mlflow
import pandas as pd

## Definir a diretoria onde as experiências são guardadas

In [2]:
from pathlib import Path

uri = "../../mlruns"

Path(uri).mkdir(parents=True, exist_ok=True)

mlflow.set_tracking_uri(uri)

# Carregar o Modelo

In [3]:
# Fazer load da versão do modelo "logistic_regression" que registamos no notebook anterior
# Têm de mudar a versão de acordo com quantas versões registaram.

model_name = "logistic_reg"
model_version = "1"
f"models:/{model_name}/{model_version}"

'models:/logistic_reg/1'

In [4]:
model = mlflow.pyfunc.load_model(f"models:/{model_name}/{model_version}")
model

mlflow.pyfunc.loaded_model:
  artifact_path: logistic_reg
  flavor: mlflow.sklearn
  run_id: cd2759b81f374fdd9cced4ef3ca7ea81

## Vamos utilizar o modelo lido para fazer previsões

In [5]:
data_path = '../../data/diabetes_test.csv'
df = pd.read_csv(data_path)

In [6]:
input_data = df.loc[df.Outcome == 1].sample(10)
input_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
111,11,143,94,33,146,36.6,0.254,51,1
3,7,150,78,29,126,35.2,0.692,54,1
97,7,195,70,33,145,25.1,0.163,55,1
8,1,147,94,41,0,49.3,0.358,27,1
54,3,171,72,33,135,33.3,0.199,24,1
45,11,135,0,0,0,52.3,0.578,40,1
87,1,196,76,36,249,36.5,0.875,29,1
95,7,184,84,33,0,35.5,0.355,41,1
89,0,107,62,30,74,36.6,0.757,25,1
79,6,124,72,0,0,27.6,0.368,29,1

In [7]:
input = input_data.drop("Outcome", axis=1)
input

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
111,11,143,94,33,146,36.6,0.254,51
3,7,150,78,29,126,35.2,0.692,54
97,7,195,70,33,145,25.1,0.163,55
8,1,147,94,41,0,49.3,0.358,27
54,3,171,72,33,135,33.3,0.199,24
45,11,135,0,0,0,52.3,0.578,40
87,1,196,76,36,249,36.5,0.875,29
95,7,184,84,33,0,35.5,0.355,41
89,0,107,62,30,74,36.6,0.757,25
79,6,124,72,0,0,27.6,0.368,29

In [8]:
model.predict(input)

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0])